name: Build and Release Docker Image  

on:  
  push:  
    branches:  
      - main  # Change this to your preferred branch  

jobs:  
  version:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Get latest tag  
        id: get_latest_tag  
        run: |  
          git fetch --tags  
          echo "latest_tag=$(git describe --tags --abbrev=0 || echo '0.0.0')" >> $GITHUB_ENV  

      - name: Bump version  
        id: bump_version  
        run: |  
          IFS='.' read -r major minor patch <<< "${{ env.latest_tag }}"  
          new_version="$major.$minor.$((patch + 1))"  
          echo "new_version=$new_version" >> $GITHUB_ENV  
          git tag "$new_version"  
          git push origin "$new_version"  

  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Log in to Docker Hub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }} 

      - name: Build the Docker image  
        
        #  working-directory: phase07/tracegouteAPI
        run: |
          docker build -t yaghooli/mygoapp:${{ env.new_version }} .
          docker push yaghooli/mygoapp:${{ env.new_version }}
          docker tag yaghooli/mygoapp:${{ env.new_version }} your-docker-repo/your-image-name:latest
          docker push yaghooli/mygoapp:latest  
