name: Bump version  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-22.04  
    permissions:  
      contents: write  
    steps:  
      - uses: actions/checkout@v4  
        with:  
          fetch-depth: '0'  

      - name: Bump version and push tag  
        id: tagstep  
        uses: anothrNick/github-tag-action@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          WITH_V: false  

      - name: Log in to Docker Hub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASS }}  

      - name: Build the Docker image  
        run: |  
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mygoapp:${{ steps.tagstep.outputs.tag }} .  
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mygoapp:${{ steps.tagstep.outputs.tag }}
